[package]
name = "jwt-gang"
version = "0.1.0"
authors = ["mich2000 <michael28072000@outlook.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.19", default-features = false }
jsonwebtoken = "7.2.0"
log = "0.4.14"
dotenv = "0.15.0"