version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ../db-data:/var/lib/postgresql/data
      - ./backend/xam-xam-dal/migrations/2020-10-09-202858_xam-xam-begin/up.sql:/docker-entrypoint-initdb.d/up.sql
    environment:
      POSTGRES_DB: ""
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
    ports:
      - "5432:5432"
  redis:
    image: sickp/alpine-redis
    command: redis-server --requirepass ""
    ports:
      - "6379:6379"
  xam-id:
    image: xam-id:staging
    depends_on:
      - db
      - redis
    ports:
      - "8000:8080"
    environment:
      DATABASE_URL: ""
      REDIS_URL: ""
      CERT_PATH: /production/live/xam-xam.xyz/fullchain.pem
      KEY_PATH: /production/live/xam-xam.xyz/privkey.pem
      PERSON_SMTP_USERNAME: ""
      PERSON_SMTP_PASSWORD: ""
      PERSON_SMTP_DOMAIN: smtp.gmail.com
    volumes:
      - /etc/letsencrypt:/production:ro
    links:
      - "db"
      - "redis"
  xam-bis:
    image: xam-bis:staging
    depends_on:
      - db
      - xam-id
    ports:
      - "8001:8081"
    volumes:
      - /etc/letsencrypt:/production:ro
    environment:
      DATABASE_URL: ""
      CERT_PATH: /production/live/xam-xam.xyz/fullchain.pem
      KEY_PATH: /production/live/xam-xam.xyz/privkey.pem
    links:
      - "db"
  xam-web:
    image: xam-web:staging
    depends_on:
      - "xam-bis"
      - "xam-id"
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/letsencrypt:/production:ro