version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./backend/xam-xam-dal/migrations/2020-10-09-202858_xam-xam-begin/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB : xam-xam
      POSTGRES_USER : xam-xam
      POSTGRES_PASSWORD : xam-xam-pwd-pg
  redis:
    image: sickp/alpine-redis
    command: redis-server --requirepass xam-xam-pwd-r
    ports:
      - "6379:6379"
  xam-id:
    image: xam-id:staging
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
      - "6379:6379"
      - "5432:5432"
    volumes:
      - "/etc/letsencrypt/live/xam-xam.xyz/:/production"
  xam-bis:
    image: xam-bis:staging
    depends_on:
      - db
      - xam-id
    ports:
      - "8001:8001"
      - "5432:5432"
    volumes:
      - "/etc/letsencrypt/live/xam-xam.xyz/:/production"
  xam-web:
    image: xam-web:staging
    depends_on:
      - "xam-bis"
      - "xam-id"
    ports:
      - "443:443"
    volumes:
      - "/etc/letsencrypt/live/xam-xam.xyz/:/production"