version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./backend/xam-xam-dal/migrations/2020-10-09-202858_xam-xam-begin/up.sql:/docker-entrypoint-initdb.d/
      environment:
        POSTGRES_DB : xam-xam
        POSTGRES_USER : xam-xam
        POSTGRES_PASSWORD : password
  redis:
    image: "alpine/redis"
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
  xam-id:
    image: "xam-xam-id"
    depends_on: 
      - db
      - redis
    ports: 
      - "8000:8000"
    volumes: 
      - "/:/etc/letsencrypt/live/xam-xam.xyz/"
  xam-bis:
    image: "xam-xam-bis"
    depends_on: 
      - db
      - xam-id
    ports: 
      - "8001:8001"
    volumes: 
      - "/:/etc/letsencrypt/live/xam-xam.xyz/"
  xam-web:
    image: "xam-xam-web"
    depends_on: 
      - "xam-bis"
      - "xam-id"
    ports: 
      - "443:443"